name: amulet_scanner
description: แอปส่องพระและเหรียญ ไม่บันทึกรูปภาพ
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  shared_preferences: ^2.5.3

flutter:
  uses-material-design: true
